config/routes.rb
Nanabozho::Application.routes.draw do
  resources :groups
  resources :users
  resources :searches

  root :to => "groups#index"

end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :description, :member_id, :name

  has_many(
    	:memberships,
    	:class_name => 'Membership',
    	:primary_key => :id,
    	:foreign_key => :group_id
    )
  has_many(
    	:users,
    	:through => :memberships,
    	:source => :user
    )

end

app/models/membership.rb
class Membership < ActiveRecord::Base
  attr_accessible :group_id, :user_id

  belongs_to(
    	:user,
    	:class_name => 'User',
    	:primary_key => :id,
    	:foreign_key => :user_id
    )
  belongs_to(
    	:group,
    	:class_name => 'Group',
    	:primary_key => :id,
    	:foreign_key => :group_id
    )
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :description, :name, :profile_image_url, :twitter_id_str, :json_str, :location

  has_many(
    	:memberships,
    	:class_name => 'Membership',
    	:primary_key => :id,
    	:foreign_key => :user_id
    )
  has_many( 
    	:groups,
    	:through => :membership,
    	:source => :group
    )
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def get_users(user_ids)
		consumer_key = OAuth::Consumer.new(
	        ENV['CONSUMER_KEY'],
	        ENV['CONSUMER_SECRET'])
	    access_token = OAuth::Token.new(
	        ENV['ACCESS_TOKEN'],
	        ENV['ACCESS_TOKEN_SECRET'])

	    users = []

		baseurl = "https://api.twitter.com"
		path    = "/1.1/users/lookup.json"
		query   = URI.encode_www_form("user_id" => user_ids.join(",")) 
		address = URI("#{baseurl}#{path}?#{query}") 

		request = Net::HTTP::Get.new address.request_uri

		http             = Net::HTTP.new address.host, address.port
		http.use_ssl     = true
		http.verify_mode = OpenSSL::SSL::VERIFY_PEER

		request.oauth! http, consumer_key, access_token
		http.start
		response = http.request request

		if response.code == '200' 
			users = JSON.parse(response.body)
		end
		return users
	end
	
	def tweets(twitter_id_str)
		consumer_key = OAuth::Consumer.new(
	        ENV['CONSUMER_KEY'],
	        ENV['CONSUMER_SECRET'])
	    access_token = OAuth::Token.new(
	        ENV['ACCESS_TOKEN'],
	        ENV['ACCESS_TOKEN_SECRET'])

	    tweets = []

		baseurl = "https://api.twitter.com"
		path    = "/1.1/statuses/user_timeline.json"
		query   = URI.encode_www_form("user_id" => twitter_id_str, "count" => 12) 
		address = URI("#{baseurl}#{path}?#{query}") 

		request = Net::HTTP::Get.new address.request_uri

		http             = Net::HTTP.new address.host, address.port
		http.use_ssl     = true
		http.verify_mode = OpenSSL::SSL::VERIFY_PEER

		request.oauth! http, consumer_key, access_token
		http.start
		response = http.request request

		if response.code == '200' 
		tweets = JSON.parse(response.body)
		end
		return tweets
	end

	protect_from_forgery
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @user_groups = []
  	groups = Group.limit(10);

    groups.each do |group|
      ids = group.users.pluck(:twitter_id_str)
      users = get_users(ids)
      @user_groups << [group, users]
    end
  end

  def show
    @group = Group.find(params[:id])
    ids = @group.users.pluck(:twitter_id_str)
    @users = get_users(ids)
  end

  def new
    @group = Group.new()
    @url = groups_url
  end

  def create
  	@group = Group.new({name: params[:group][:name], description: params[:group][:description]})
  	if @group.valid? 
  	 	@group.save!	
      params[:group][:users].each do |id_str|
        @user = User.new({
            twitter_id_str: id_str 
        })
        if @user.valid?
          @user.save! 
          Membership.create!({group_id: @group.id, user_id: @user.id})
        end
      end
      redirect_to group_url(@group)
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
    ids = @group.users.pluck(:twitter_id_str)
    @users = get_users(ids)
    @url = group_url(@group)
  end

  def update
    @group = Group.find(params[:id])
    @group.name = params[:group][:name]
    @group.description = params[:group][:description]
    if @group.valid?
      @group.save!
    end

    existing_users = @group.users.pluck(:twitter_id_str)
    future_users = []

    params[:group][:users].each do |id_str|
      future_users << id_str
      @user = User.find_by_twitter_id_str(id_str)
      if @user # user is already in the db
        unless existing_users.include?(id_str) #add membership too if user's not part of current group
          Membership.create!({group_id: @group.id, user_id: @user.id})
        end
      else # new and therefore not group member
        @user = User.new({twitter_id_str: id_str})
        if @user.valid?
          @user.save!
          Membership.create!({group_id: @group.id, user_id: @user.id})
        end
      end
    end
    
    #delete memberships 
    members_to_delete = existing_users.select { |user| !future_users.include?(user) }
    members_to_delete.each do |id_str|
      @user = User.find_by_twitter_id_str(id_str)
      @membership = Membership.find_by_group_id_and_user_id(@group.id, @user.id)
      @membership.destroy
    end
    ids = @group.users.pluck(:twitter_id_str)
    @users = get_users(ids)

    render :show
  end
  
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

	def new

	end

	def create
		@user = params[:user]

		 	consumer_key = OAuth::Consumer.new(
		       ENV['CONSUMER_KEY'],
		       ENV['CONSUMER_SECRET'])
		   access_token = OAuth::Token.new(
		       ENV['ACCESS_TOKEN'],
		       ENV['ACCESS_TOKEN_SECRET'])

		baseurl = "https://api.twitter.com"
		path    = "/1.1/users/search.json"
		query   = URI.encode_www_form("q" => @user['name'], "page" => @user['page'])
		address = URI("#{baseurl}#{path}?#{query}")

		request = Net::HTTP::Get.new address.request_uri

		http             = Net::HTTP.new address.host, address.port
		http.use_ssl     = true
		http.verify_mode = OpenSSL::SSL::VERIFY_PEER

		request.oauth! http, consumer_key, access_token
		http.start
		response = http.request request

		@users = nil
		if response.code == '200' 
		  @users = JSON.parse(response.body)
		end

		render :json => @users
	end

	def show
		

	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def new

	end

	def show
		@tweets = tweets(params[:id])
		render :json => @tweets
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_group_column.html.erb
<% @groups.each do |group| %>
	<% users = group[1] %>
	<div class="groupbox">
		<div class="userbox">
			<% 6.times do |j| %>
				<% if j == 3 %>
					<br>
				<% end %>
				<% if j < users.size %>
					<img src="<%= users[j]['profile_image_url'] %>" title="<%= users[j]['name'] %>"></img>
				<% else %>
					<img src="https://1.gravatar.com/avatar/c9b64f924b5712b51388ff5a1222be6e?d=https%3A%2F%2Fidenticons.github.com%2F0338500963cd12807e2d5154305c44f9.png&amp;r=x&amp;s=440" title="Buchowski"></img>
				<% end %>
			<% end %>
		</div>
		<h4><a href="<%= group_url(group[0]) %>"><%= group[0].name %></a></h4>
		<p>by Buchowski</p>
		<p><%= users.size %> members</p>
	</div>
<% end %>

app/views/groups/_group_form.html.erb
<form class="form-horizontal" role="form" action="<%= @url %>" method="POST">
	<% if @url != groups_url %>
		<input type="hidden" name="_method" value="PUT"></input>
	<% end %>
	<div class="form-group">
		<label class="control-label" for="group_name">Name</label>
		<div>
			<input class="form-control" type="text" maxlength="15" name="group[name]" id="group_name" value="<%= @group.name %>" placeholder="What's your group's name?"></input>
		</div>
	</div>
	<div class="form-group">
		<label class="control-label" for="group_description">Description</label>
		<div>
			<textarea class="form-control" name="group[description]" id="group_description" placeholder="How would you describe your group?"><%= @group.description %></textarea>
		</div>
	</div>
	<div class="form-group">
		<button type="submit" class="btn btn-default">Submit</button>
	</div>
	<!-- this div holds each user's hidden input tag -->
	<div id="users_to_add"></div> 
</form>

app/views/groups/_login_form.html.erb
<form class="form-horizontal">
	<div class="form-group">
		<label for="email" class="control-label">Email</label>
		<input id="email" class="form-control" name="guest[email]" placeholder="Currently Disabled">
	</div>
	<div class="form-group">
		<label for="password" class="control-label">Password</label>
		<input id="password" class="form-control" name="guest[password]" placeholder="Currently Disabled">
	</div>
	<div class="form-group">
		<button id="login" type="submit" class="btn btn-default">Log In</button>
	</div>
</form>
<script type="text/javascript">
	$("#login").on("click", function (e) {
		e.preventDefault();
		alert("Login is currently disabled.")
	})
</script>

app/views/groups/_manage_group.html.erb
<div class="col-md-10">
	<h1>Enter Group Information</h1>
	<div class="row">
		<div class="col-md-6">
			<%= render 'group_form' %>
		</div>
	 	<div class="col-md-6">
			<label class="control-label">Current Users</label>
			<div class='user_div' id="current_members"></div>
		</div>
	</div>
	<hr>
	<%= render 'search_form' %>
</div>
<div class="col-md-2">
	<h1>Log In</h1>
	<%= render 'login_form' %>
</div>

app/views/groups/_search_form.html.erb
<div class="row">
	<h1>Search for your group's Twitterers</h1>
	<!-- <div class="clearfix"></div> -->
	<form action="<%= searches_url %>" method="POST" id="search_form" class="form-inline" role="form">
		<div class="form-group">
			<label class="sr-only" for="user_name">User Search</label>
			<input class="form-control" type="text" name="user[name]" id="user_name" placeholder="Search Term">
		</div>
		<input id="page_num" type='hidden' name="user[page]" value='1'>
		<button type="submit" class="btn btn-default">Search</button>
	</form>

	<h2 class='inline'>Search Results</h2>
	<a id="prev_page" class='change_page disabled' href="">Prev</a>
	<a id="next_page" class='change_page' href="">Next</a>	
</div>
<div class="row">
	<div class='searched_users col-md-6' id="searched_users_0"></div>
	<div class='searched_users col-md-6' id="searched_users_1"></div>
</div>

<script type="text/javascript">
	$(function () {
		$("#page_num").val('1');
	})
</script>

app/views/groups/create.html.erb
<h1>Groups#create</h1>
<p>Find me in app/views/groups/create.html.erb</p>

app/views/groups/edit.html.erb
<%= render 'manage_group' %>

<script type="text/javascript">
	$(function () {
		$("#page_num").val('1');
		$('#users').toggleClass('none', false);
		<% @users.each do |user| %>
			$("#users_to_add").append(hidden_template(<%= {
				twitter_id_str: user['id_str']
			}.to_json.html_safe %>));

			$("#current_members").append(template(<%= {
				profile_image_url: user['profile_image_url'], 
				name: user['name'], 
				id_str: user['id_str'],
				location: user['location']
			}.to_json.html_safe %>));
		<% end %>
	})
</script>

app/views/groups/index.html.erb
<div class="container">
	<div class="col-md-10">
		<h1>Click a Group</h1>
		<% mid = @user_groups.size / 2 %>
		<% left_group, right_group = @user_groups[0...mid], @user_groups[mid..-1] %>

		<div id="left_group" class="col-md-6">
			<% @groups = left_group %>
			<%= render 'group_column' %>
		</div>
		<div id="right_group" class="col-md-6">
			<% @groups = right_group %>
			<%= render 'group_column' %>
		</div>
	</div>
	<div class="col-md-2">
		<h1>Log In</h1>
		<%= render 'login_form' %>
	</div>
</div>

	

app/views/groups/new.html.erb
<%= render 'manage_group' %>

app/views/groups/show.html.erb
<div class="container">
	<div class="col-md-10">
		<h1><%= @group.name %></h1>
		<p>Description: <%= @group.description %></p>
		<h1>Click to view a user's tweets</h1>

		<% mid = @users.size / 2 %>
		<% left_users, right_users = @users[0...mid], @users[mid..-1] %>

		<div id="left_users" class="col-md-6">
			<% @users = left_users %>
			<%= render 'users/users_column' %>
		</div>
		<div id="right_users" class="col-md-6">
			<% @users = right_users %>
			<%= render 'users/users_column' %>
		</div>
	</div>
	<div class="col-md-2">
		<h1>Log In</h1>
		<%= render 'login_form' %>
	</div>
</div>
<script type="text/javascript">
	var MONTH = {0: 'Jan', 1: 'Feb', 2: 'Mar', 3: 'Apr', 4: 'May', 5: 'Jun', 
					6: 'Jul', 7: 'Aug', 8: 'Sep', 9: 'Oct', 10: 'Nov', 11: 'Dec'};
	function ajax(twitter_id_str) {
		$.ajax({
			url: '/users/' + twitter_id_str,
			type: 'GET',
			dataType: 'json',
			success: function (response) {
				if (response.length == 0) {
					$("#" + twitter_id_str + " > table").append("<tr><td>No Hay Tweet</td></tr>");
				} else {
					show(twitter_id_str, response)
				}
			},
			error: function (response) {
				console.log('ERROR: ' + response);
			}
		})
	}
	function show(twitter_id_str, response) {
		_.each(response, function (tweet) {
			var tweet_date = new Date(Date.parse(tweet['created_at']));
			var display_time = MONTH[tweet_date.getMonth()] + " " + tweet_date.getDate();
			$("#" + twitter_id_str + " > table").append(tweet_template(tweet, display_time));
		})
		$("a[name*='" + twitter_id_str + "']").off().on("click", hide);
	}
	function hide() {
		$("#" + $(this).attr("name") + " > table").slideToggle(600);
	}
	$( function () {
		// $('#header_links').append("<a href='<%#= edit_group_url %>'>Edit This Group</a>");
		$(".user > a").on("click", function () {
			ajax($(this).attr("name"));
		})
	})
</script>
<script type="text/javascript">
	$(function () {
		$("ul.nav").append("<li class='active'><a href='<%= edit_group_url %>'>Edit This Group</a></li>")
		// $("ul.nav").append("King Kong");
	})
</script>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">				
				<a class="navbar-brand" href="<%= groups_url %>">Nanabozho</a>
			</div>
			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav">
					<li class="active">
						<a href="<%= new_group_url %>">Create New Group</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nanabozho</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="content container">
	<%= render 'layouts/header' %>
	<%= yield %>
</div>
</body>
</html>

app/views/searches/create.html.erb
<form action="<%= groups_url %>" method="POST">
	<input type="submit" value="Add Selected Users to Group"></input>

	<% @users.each_with_index do |user, i| %>
	<!-- :description, :name, :profile_image_url, :twitter_id_str -->
		<img src="<%= user['profile_image_url'] %>">
		<h3><%= "#{user['name']} #{user['location']}" %></h3>
		<input type="checkbox" name="user[<%= i %>]" value="<%= user.to_json %>"></input>
	<% end %>

</form>

app/views/searches/new.html.erb
<form action="<%= searches_url %>" method="POST">
	<label for="">User Search</label>
	<input type="text" name="user[name]" id="user_name">
	<input type="submit" value="Search">
</form>

app/views/users/_users_column.html.erb
<% @users.each do |user| %>
	<div class="user" id="<%= user['id'] %>">
		<img src="<%= user['profile_image_url'] %>">
		<a name="<%= user['id'] %>"><%= user['name'] %></a>
		<table class='table table-striped'></table>
	</div>
<% end %>

app/views/users/index.html.erb
#New user